name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}               # Public IP or DNS of AWS
          username: ${{ secrets.AWS_USER }}           # Usually "AWS-user" for Amazon Linux or "ubuntu" for Ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}             # Private key (.pem) stored as GitHub Secret
          script: |
            chmod +x ~/deploy-backend.sh
            ~/deploy-backend.sh

      - name: Send Telegram notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="✅ Heyy SURESH! Backend deployment (TinderDEV) to AWS EC2 completed successfully from *main* branch!" \
            -d parse_mode=Markdown
